### ISSUE TITLE
Helmet and Armor

### ISSUE THREAD

**Issue by tman540** [tman540/T.A.R.B.S.-Engine#19]
Equipable armor and helmet that add extra protection.

**Comment by GriffinAustin** [comment]
Hey @tman540, wondering if I could take this, or at least help you with, this issue? Let me know and I can start working on it.

**Comment by tman540** [comment]
@GriffinAustin Sure, just download the code, and send me what you come up with. Tommorow, I'll add you as a contributer!

**Comment by GriffinAustin** [comment]
@tman540 Just created a pull request, let me know your thoughts!

**Comment by GriffinAustin** [comment]
@tman540 Yeah, my discord is griffin#9034

**Comment by tman540** [comment]
@GriffinAustin added you

**Comment by tman540** [comment]
### **Added**
